### ISSUE TITLE
Atualização do Documento de Visão.

### ISSUE THREAD

**Issue by Brunowcst** [Brunowcst/SistemasDeControleDePontos#21]
# Atualização no documento de visão

- [x] Correção nos requisitos funcionais. (Marcelo)
> - Renomear usuário para funcionário em todo escopo do documento.
>  - Análise se é necessário ou se existe mais algum requisito que possa ser implementado.

- [x] Correção no esquema relacional. (David e Renan)
>  - Pensar sobre tabelas, relacionamentos e atributos que podem ser necessários. Dica do orientador: simular uma ação que utilize as tabelas, assim é possível descobrir se existem problemas no esquema.

- [x] Análise da tabela de riscos. (Marcelo)
> - Pensar sobre novos possíveis riscos.

**Comment by RenanValed** [comment]
Qual a branch para usar nesse documento?

**Comment by Brunowcst** [comment]
Criem branchs novas
